version: "3.9"
services:
  web:
    image: 301740015/test:test
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    container_name: web

  nginx:
    image: 301740015/test:nginx_pass
    ports:
      - "5050:80"
    links:
      - web:web
    depends_on:
      - web